name: Unit Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Lint with pylint
      run: |
        pip install django
        pip install djangorestframework
        pip install djangorestframework-simplejwt
        pip install drf-yasg
        pip install boto3
        pip install django-fernet-fields
        pip install django-storages
        pip install pylint
        pip install pylint-django
        pip install pylint-runner
        pip install pylint-exit
        pylint_runner --rcfile=.pylintrc || pylint-exit $?
        if [ $? -ne 0 ]; then
          echo "An error occurred while running pylint." >&2
          exit 1
        fi
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run pytest tests
      run: |
        # pip install pytest
        # python -m pytest
